EXPLAIN PLAN SET STATEMENT_ID = 'ST_BEFORE' FOR 
SELECT /*+FULL(LOADINGS) FULL(TRUCKS)*/ TRUCK_PLATE_NR, LOADINGS.STARTING_TIME, LOADINGS.GATE_NR
FROM LOADINGS inner join TRUCKS on LOADINGS.TRUCK_PLATE_NR = TRUCKS.PLATE_NR where (TRUCKS.CAPACITY > 500 AND TRUCKS.RANGE > 800 );

SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());
-----------------------------------------------
EXPLAIN PLAN SET STATEMENT_ID = 'ST_BEFORE1' FOR 
SELECT /*+INDEX(LOADINGS) INDEX(TRUCKS)*/ TRUCK_PLATE_NR, LOADINGS.STARTING_TIME, LOADINGS.GATE_NR
FROM LOADINGS inner join TRUCKS on LOADINGS.TRUCK_PLATE_NR = TRUCKS.PLATE_NR where (TRUCKS.CAPACITY > 500 AND TRUCKS.RANGE > 800 );

SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());
------------------------------------------------
EXPLAIN PLAN SET STATEMENT_ID = 'ST_BEFORE2' FOR 
SELECT /*+INDEX_FFS(LOADINGS) INDEX_FFS(TRUCKS)*/ TRUCK_PLATE_NR, LOADINGS.STARTING_TIME, LOADINGS.GATE_NR
FROM LOADINGS inner join TRUCKS on LOADINGS.TRUCK_PLATE_NR = TRUCKS.PLATE_NR where (TRUCKS.CAPACITY > 500 AND TRUCKS.RANGE > 800 );

SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());
-------------------------------------------------------
EXPLAIN PLAN SET STATEMENT_ID = 'ST_BEFORE3' FOR 
SELECT /*+USE_NL(LOADINGS TRUCKS)*/ TRUCK_PLATE_NR, LOADINGS.STARTING_TIME, LOADINGS.GATE_NR
FROM LOADINGS inner join TRUCKS on LOADINGS.TRUCK_PLATE_NR = TRUCKS.PLATE_NR where (TRUCKS.CAPACITY > 500 AND TRUCKS.RANGE > 800 );

SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());
----------------------------------------------------------



EXPLAIN PLAN SET STATEMENT_ID = 'ST_AFTER' FOR 
SELECT /*+USE_MERGE(LOADINGS TRUCKS)*/ TRUCK_PLATE_NR, LOADINGS.STARTING_TIME, LOADINGS.GATE_NR
FROM LOADINGS inner join TRUCKS on LOADINGS.TRUCK_PLATE_NR = TRUCKS.PLATE_NR where (TRUCKS.CAPACITY > 500 AND TRUCKS.RANGE > 800 );

SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());
-----------------------------------------------
 EXPLAIN PLAN SET STATEMENT_ID = 'ST_AFTER' FOR 
SELECT /*+USE_HASH(LOADINGS TRUCKS)*/ TRUCK_PLATE_NR, LOADINGS.STARTING_TIME, LOADINGS.GATE_NR
FROM LOADINGS inner join TRUCKS on LOADINGS.TRUCK_PLATE_NR = TRUCKS.PLATE_NR where (TRUCKS.CAPACITY > 500 AND TRUCKS.RANGE > 800 );

SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());
-----------------------------------------------
